---
abstract: 'supporting for application process monitoring, as defined by opentelemetry.io'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.94'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OpenTelemetry
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  OpenTelemetry:
    file: lib/OpenTelemetry.pm
    version: '0.001'
  OpenTelemetry::Any:
    file: lib/OpenTelemetry/Any.pm
    version: '0.001'
requires:
  OpenTracing: '0'
  indirect: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/OpenTelemetry/issues
  homepage: https://github.com/team-at-cpan/OpenTelemetry
  repository: https://github.com/team-at-cpan/OpenTelemetry.git
version: '0.001'
x_authority: cpan:TEAM
x_generated_by_perl: v5.30.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
